
# spring.application.name=jpa

server:
  port: 8181

spring:
  application:
    name: jpa
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html


jwt:
  secret: 634/l8dGvUl2N2AkfKuEHRwOITywis7KB5TOlVR49tNqDPzfL5T34z+cGJvUHcJ9wPR6EhGILRGxLEm1kQ5gKQ==